import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { FaGithub, FaLinkedin, FaEnvelope } from "react-icons/fa";
import { portfolio } from "@/config/portfolio";
import "./Footer.scss";
export var Footer = function () {
    var _a, _b;
    return (_jsxs("footer", { className: "footer", children: [_jsxs("div", { className: "footer-content", children: [_jsxs("div", { className: "footer-info", children: [_jsx("h3", { children: portfolio.firstName }), _jsx("p", { children: portfolio.description })] }), _jsxs("div", { className: "footer-links", children: [_jsx("h4", { children: "Quick Links" }), _jsxs("ul", { children: [_jsx("li", { children: _jsx("a", { href: "#about", children: "About" }) }), _jsx("li", { children: _jsx("a", { href: "#skills", children: "Skills" }) }), _jsx("li", { children: _jsx("a", { href: "#projects", children: "Projects" }) }), _jsx("li", { children: _jsx("a", { href: "#experience", children: "Experience" }) }), _jsx("li", { children: _jsx("a", { href: "#contact", children: "Contact" }) })] })] }), _jsxs("div", { className: "footer-social", children: [_jsx("h4", { children: "Connect With Me" }), _jsxs("div", { className: "social-icons", children: [((_a = portfolio.social) === null || _a === void 0 ? void 0 : _a.github) && (_jsx("a", { href: portfolio.social.github, target: "_blank", rel: "noopener noreferrer", "aria-label": "GitHub", children: _jsx(FaGithub, {}) })), ((_b = portfolio.social) === null || _b === void 0 ? void 0 : _b.linkedin) && (_jsx("a", { href: portfolio.social.linkedin, target: "_blank", rel: "noopener noreferrer", "aria-label": "LinkedIn", children: _jsx(FaLinkedin, {}) })), portfolio.email && (_jsx("a", { href: "mailto:".concat(portfolio.email), "aria-label": "Email", children: _jsx(FaEnvelope, {}) }))] })] })] }), _jsx("div", { className: "footer-bottom", children: _jsxs("p", { children: ["\u00A9 ", new Date().getFullYear(), " ", portfolio.firstName, " ", portfolio.lastName, ". All Rights Reserved."] }) })] }));
};
export default Footer;
